import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FB",
    padding: 20,
  },
  searchBarRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  inputSearch: {
    flex: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 15,
    color: "#1A1A2E",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  botaoFiltro: {
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    height: 52,
    width: 52,
    position: "relative",
  },
  botaoFiltroInativo: {
    backgroundColor: "#fff",
    borderColor: "#E2E8F0",
  },
  botaoFiltroAtivo: {
    backgroundColor: "#EEEDFE",
    borderColor: "#AFA9EC",
  },
  iconFunilContainer: {
    width: 18,
    height: 12,
    justifyContent: "space-between",
  },
  iconFunilLinhaGrande: {
    height: 2,
    backgroundColor: "#1A56DB",
    width: "100%",
  },
  iconFunilLinhaMedia: {
    height: 2,
    backgroundColor: "#1A56DB",
    width: "70%",
    alignSelf: "center",
  },
  iconFunilLinhaPequena: {
    height: 2,
    backgroundColor: "#1A56DB",
    width: "40%",
    alignSelf: "center",
  },
  badgeFiltro: {
    position: "absolute",
    top: -4,
    right: -4,
    backgroundColor: "#EF9F27",
    borderRadius: 10,
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeFiltroTexto: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "bold",
  },
  botaoBuscar: {
    backgroundColor: "#1A56DB",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 20,
    shadowColor: "#1A56DB",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  textoBotao: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
    letterSpacing: 0.3,
  },
  filterSection: {
    marginBottom: 18,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  chipRow: {
    flexDirection: "row",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#fff",
  },
  chipText: {
    fontSize: 13,
    color: "#64748B",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    maxHeight: "75%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 22,
  },
  modalTitulo: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A2E",
  },
  botaoLimparFiltros: {
    color: "#EF4444",
    fontWeight: "600",
    fontSize: 14,
  },
  botaoAplicarModal: {
    backgroundColor: "#1A56DB",
    padding: 15,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 15,
  },
  textoBotaoAplicarModal: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  listContainer: {
    paddingTop: 10,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  nome: {
    fontWeight: "700",
    fontSize: 16,
    color: "#1A1A2E",
    marginBottom: 2,
  },
  subNome: {
    fontSize: 13,
    color: "#94A3B8",
    marginBottom: 4,
  },
  tagRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 8,
    flexWrap: "wrap",
  },
  tag: {
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    fontWeight: "600",
    overflow: "hidden",
  },
  tagTipo: {
    backgroundColor: "#EEF2FF",
    color: "#4338CA",
  },
  tagGenero: {
    backgroundColor: "#ECFDF5",
    color: "#065F46",
  },
  tagEstilo: {
    backgroundColor: "#FFFBEB",
    color: "#92400E",
  },
  empty: {
    textAlign: "center",
    color: "#94A3B8",
    marginTop: 60,
    fontSize: 14,
    fontWeight: "500",
    paddingHorizontal: 20,
  },
});